# Generated by cpp11: do not edit by hand

Ctest <- function(input) {
  .Call(`_dtutils_Ctest`, input)
}

Crle_cpp <- function(x) {
  .Call(`_dtutils_Crle_cpp`, x)
}

Cnfirst_by <- function(x) {
  .Call(`_dtutils_Cnfirst_by`, x)
}

Cfirst_by <- function(n, rows, grps) {
  .Call(`_dtutils_Cfirst_by`, n, rows, grps)
}

Clast_by <- function(n, rows, grps) {
  .Call(`_dtutils_Clast_by`, n, rows, grps)
}

Crow_number_by <- function(n, rows, grps) {
  .Call(`_dtutils_Crow_number_by`, n, rows, grps)
}
