# Generated by cpp11: do not edit by hand

Cfirst_by <- function(n, rows, grps) {
  .Call(`_dtutils_Cfirst_by`, n, rows, grps)
}

Clast_by <- function(n, rows, grps) {
  .Call(`_dtutils_Clast_by`, n, rows, grps)
}

Crow_number_by <- function(n, rows, grps) {
  .Call(`_dtutils_Crow_number_by`, n, rows, grps)
}
