# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Ccoalesce_by <- function(x, rows, names) {
    .Call('_dtutils_Ccoalesce_by', PACKAGE = 'dtutils', x, rows, names)
}

Ccumope_by <- function(x, rows, type) {
    .Call('_dtutils_Ccumope_by', PACKAGE = 'dtutils', x, rows, type)
}

Cna_fill_by <- function(x, rows, type = 1L, inplace = FALSE, fill = NULL) {
    .Call('_dtutils_Cna_fill_by', PACKAGE = 'dtutils', x, rows, type, inplace, fill)
}

Crow_number_by <- function(n, rows) {
    .Call('_dtutils_Crow_number_by', PACKAGE = 'dtutils', n, rows)
}

Cfirst_by <- function(n, rows) {
    .Call('_dtutils_Cfirst_by', PACKAGE = 'dtutils', n, rows)
}

Clast_by <- function(n, rows) {
    .Call('_dtutils_Clast_by', PACKAGE = 'dtutils', n, rows)
}

Cany_by <- function(x, rows) {
    .Call('_dtutils_Cany_by', PACKAGE = 'dtutils', x, rows)
}

Call_by <- function(x, rows) {
    .Call('_dtutils_Call_by', PACKAGE = 'dtutils', x, rows)
}

Cweightedsum <- function(x, wt, rows, na_rm) {
    .Call('_dtutils_Cweightedsum', PACKAGE = 'dtutils', x, wt, rows, na_rm)
}

